import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import { Provider } from "react-redux";
import { store } from "./component/redux/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="w-11/12 mx-auto" data-theme="light" id="tanvir" >
      <body className={inter.className} >
      <Navbar/>
      
      {children}
      
        </body>
    </html>
  );
}
