import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import { Providers } from "./redux/provider";
import { AuthProvider } from "./Provider";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light" className=" bg-[#EFF0F5]">
      <body className={`${inter.className}`} >
      <Providers>
        <AuthProvider>
        <Navbar/>
        <div className="mx-auto">
        {children}
        </div>
        
        </AuthProvider>
      </Providers>
        </body>
    </html>
  );
}
